# Generated by Django 5.2 on 2025-04-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_category_remove_course_subject_delete_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
